config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testitwinaiplugins:
      branch: main
      repo: https://github.com/PalomoIFCA/testitwinaiplugins
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-gamboge-vole.sh
        container: qc.acc_cloudy-ruby-catfish
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-eggplant-binturong.sh
        container: qc.doc_woolly-thistle-neanderthal
      github.com/PalomoIFCA/testitwinaiplugins git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-khaki-seal.sh
        container: qc.doc_shaky-razzmatazz-spitz
      github.com/PalomoIFCA/testitwinaiplugins markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olivine-chinchilla.sh
        container: qc.doc_sleepy-red-zebu
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-lemon-salamander.sh
        container: qc.lic_zippy-teal-bear
  QC.Met:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-wisteria-buzzard.sh
        container: qc.met_cranky-cyan-capybara
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-sponge.sh
        container: qc.sec_gamy-olive-squid
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-denim-kudu.sh
        container: qc.sty_homely-magnolia-monkey
      github.com/PalomoIFCA/testitwinaiplugins hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-jade-moth.sh
        container: qc.sty_snoopy-cerulean-anteater
      github.com/PalomoIFCA/testitwinaiplugins jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-linen-hippopotamus.sh
        container: qc.sty_chewy-amber-mouse
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins commands:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-fuchsia-chamois.sh
        container: qc.uni_snippy-emerald-binturong
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testitwinaiplugins get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cream-dragon.sh
        container: qc.ver_scummy-lavender-goat
timeout: 5400
